### ISSUE TITLE
Future TODO wishlist

### ISSUE THREAD

**Issue by kpander** [kpander/mp3tag#7]
This issue simply tracks potential future functionality. Not prioritized, not detailed. If any of these are going to be implemented, create a new proper issue for them and remove from this list.

- [ ] `--list` should be able to specify a filename, rather than assuming first file in the folder
- [ ] `--list` could export in a format other than `info.txt`, e.g. JSON
- [ ] I should be able to `--list` a specific filename (path/to/file) and not need to also specify a `/path/to/folder`
  - e.g., `$ tag --list /path/to/file.mp3`
- [ ] `--export-cover` could export an existing cover art image to a file on disk
- [ ] `--no-common` should ignore removing common text during renaming
- [ ] if I don't supply a path, it should assume the current working directory
  - maybe reconsider this
  - the reason we require a path is so that we don't just immediately tag files in the current folder if we just type `tag`
  - maybe the default should be `--dry-run` and we have to pass a switch to apply changes?
